version: "3"
services:
    web:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        links:
            - mysql
    mysql:
        image: mysql:5.7
        env_file: .env
        volumes:
            - ./mysql:/var/lib/mysql
    redis:
        restart: always
        image: redis:alpine
